#!/bin/bash
# Caminho do próprio AppRun
HERE="$(dirname "$(readlink -f "$0")")"

# Define a raiz do AppImage como APPDIR
export APPDIR="$HERE/usr"

# Redireciona o caminho padrão de trabalho para dentro do AppImage
cd "$APPDIR"

# Executa o jogo
exec "$HERE/usr/bin/canga_survivors-linux" "$@"

